#!/bin/bash
set -m
. ~/repos/dotfiles/dot_bashrc_functions
. ~/repos/dotfiles/docker_aliases.sh
# . ~/repos/dotfiles/docker_aliases.sh

function con()
{
    conda activate $1
    condap
}


export rm="${HOME}/Dropbox/phil_files/readmes"
export or="${HOME}/Dropbox/phil_files/org"
export a301="${HOME}/repos/a301_eoas"
export a301old="${HOME}/repos/a301_students_eoas"
export a301drop="${HOME}/Dropbox/phil_files/a301"
export e340=${HOME}/Dropbox/phil_files/e340_2022_RHW
export n340=${HOME}/Nextcloud/e340_2022
#echo "through .bashrc"
export CARGO_HOME=${HOME}/.cargo
export RUSTUP_HOME=${HOME}/.rustup

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/phil/mini310/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/phil/mini310/etc/profile.d/conda.sh" ]; then
        . "/Users/phil/mini310/etc/profile.d/conda.sh"
    else
        export PATH="/Users/phil/mini310/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


# Created by `userpath` on 2023-01-16 19:22:05
export PATH="${HOME}/.local/bin:$PATH"
export PYDEVD_DISABLE_FILE_VALIDATION=1

export PATH="${HOME}/Applications/quarto/bin:$PATH"
. "$HOME/.cargo/env"
con a301
